### ISSUE TITLE
Add -prod monitoring to nagios

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/folio-graphql#133]

**Comment by jcoyne** [comment]
https://www.apollographql.com/docs/apollo-server/monitoring/health-checks/

**Comment by jcoyne** [comment]
To be implemented by ops:  https://github.com/sul-dlss/operations-tasks/issues/3643

**Comment by jcoyne** [comment]
fixed: https://sul-nagios-prod.stanford.edu/nagios/cgi-bin/extinfo.cgi?type=2&host=sul-folio-graphql-prod&service=sul-folio-graphql-prod%3Anagios-prod+check_webapp
