### ISSUE TITLE
Productionize folio-graphql endpoint

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/folio-graphql#15]
The FOLIO graphql endpoint is still insufficient for mylibrary (and requests?). 

- [x] Promote our spike (http://github.com/sul-dlss-labs/folio-graphql/) to sul-dlss
- [x] figure out where/how to deploy it and make appropriate environments
- [x] deploy it for folio-test ~and folio-prod environments~.
- [x] add honeybadger 
- [ ] secure it #21 
- [ ] #23
- [ ] #24

**Comment by cbeer** [comment]
I've split off tickets for some remaining work.
