### ISSUE TITLE
Restrict access to the graphql data

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/folio-graphql#21]
Information returned by graphql needs to be protected either to trusted hosts or (preferably) using some kind of authn/authz.

Maybe we can send over the folio user credentials as basic auth? Or login and get a token from FOLIO that we can send over?

**Comment by jcoyne** [comment]
@cbeer whom should it be restricted to?  Do we need to set up authn/authz for this or will iptables suffice?

**Comment by cbeer** [comment]
Either might do. I think sending over the OKAPI credentials or token would be preferred so we can test things locally?

**Comment by jcoyne** [comment]
I'm not sure how we could pass the OKAPI credentials through, as the ApolloServer needs to have it's resolvers set up outside of the request context. https://github.com/sul-dlss/folio-graphql/blob/main/server.mjs#L21-L26

**Comment by cbeer** [comment]
It looks like there's a way to pass in run-time information to resolvers?
https://www.apollographql.com/docs/apollo-server/data/resolvers#the-contextvalue-argument

Maybe there's other ways too.

**Comment by jcoyne** [comment]
Was this done via https://github.com/sul-dlss/puppet/commit/16e5c0c3385f87c606c93acfdcb0b71639dc6f70 ?

**Comment by cbeer** [comment]
I hope we can do better. Exploring any of Apollo's built-in authentication mechanisms seems useful to me... it'd be nice to not depend on network security, and it'd be nice if we could access the graphql endpoint for development.
