### ISSUE TITLE
get it in weekly dependency updates

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/folio-graphql#23]

**Comment by jcoyne** [comment]
@cbeer isn't this already done? https://github.com/sul-dlss/access-update-scripts/blob/f1c820367847f7b9c24429fb825685f4f7be1f82/access/projects.yml#L9

**Comment by cbeer** [comment]
Cool. I just looked at the spreadsheet and expected to see a row there. I guess we'll have to add it next week.
