### ISSUE TITLE
How do we parse loan policies to get useful information?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/folio-graphql#34]
We want to tell:
- whether an item is currently renewable
- the earliest date an item can be renewed
- how long the renewal is for
- how many times an item can be renewed
- whether an item is a short-term loan (hourly) (or on reserve?)

**Comment by thatbudakguy** [comment]
- whether an item is currently renewable

folio loan policies have a simple boolean called `renewable`, but that doesn't take account of any properties of the item itself. for a `Symphony::Checkout`, we determine renewability by exhaustively checking each reason why the item might _not_ be renewable (`#non_renewable_reason`); if there are none, it is by definition renewable.

to do the same thing for a `Folio::Checkout`, we would need to implement:
- `Folio::Checkout#lost?`
- `Folio::Checkout#recalled?`
- `Folio::Checkout#claimed_returned?`
- `Folio::Checkout#unseen_renewals_remaining` (this has to do with online renewals vs. in person)
- `Folio::Checkout#seen_renewals_remaining` (i.e. in person and not online)
- `Folio::Checkout#renewable_at` (see below)

some of the other conditions checked in `non_renewable_reason` probably _are_ provided by the loan policy:
- `Folio::Checkout#reserve_item?`
- `Folio::Checkout#item_category_non_renewable?`

either or both of these might be covered by `renewable` being `false` on the loan policy.

**Comment by thatbudakguy** [comment]
_the earliest date an item can be renewed_ - `Folio::Checkout#renewable_at`

folio loan policies have a string field called `renewalsPolicy.renewFromId` described as the "Renew from date". we currently only have one loan policy that has this field defined, and it's set to the string `SYSTEM_DATE`. i don't really know what this means...maybe it's a reference to another field on the loan object itself?

**Comment by thatbudakguy** [comment]
_how long the renewal is for_

for items where renewals have the same length as regular checkouts, this information is an object stored at `loansPolicy.period` on the loan policy:
```js
"loansPolicy": {
   "period": { "duration": 28, "intervalId": "Days" },
}
```

some loan policies can also specify an alternate time length for renewals, which supersedes the length of a regular checkout. if present, that information is in `renewalsPolicy`:
```js
"renewalsPolicy": {
   "differentPeriod": true,
   "period": { "duration": 5, "intervalId": "Days" },
}
```
we don't currently have any policies with a different length for renewals.

**Comment by thatbudakguy** [comment]
_how many times an item can be renewed_

the total number of allowed renewals is `renewalsPolicy.numberAllowed` on the loan policy. the number of renewals the patron has used up for that particular item is `renewalCount` on the checkout object.

for the `seen_renewals_remaining` and `unseen_renewals_remaining` methods, one might be able to use the loan history API at `/loan-storage/loan-history` and pass a CQL query that filters to just renewal events for the particular loan, and then checks the `checkoutServicePointId` for those events to determine if the service point was a physical location? it doesn't seem like folio has a concept that maps to this.

**Comment by thatbudakguy** [comment]
_whether an item is a short-term loan (hourly) (or on reserve?)_

for a `Symphony::Checkout` we do this by looking up the loan period against a table of known short term loan periods (currently just `HOURLY`). we could do the same thing using `loansPolicy.period` for a `Folio::Checkout`. folio's concept of short term is "anything less than one day", so we could set:
```ruby
SHORT_TERM_LOAN_PERIODS = %w[Minutes Hours].freeze
```
...since these values are part of a controlled vocabulary in folio.

there's currently no information in a loan policy that identifies it as being specifically for a reserve item (although we do usually put something in the description field about it).
```js
"name": "28day-2renew-1daygrace-2item",
"description": "28-day course reserves loan for Lane with 2-item limit",
```

**Comment by cbeer** [comment]
Thanks; I've transferred this research into https://github.com/sul-dlss/mylibrary/issues/825 for implementation.

I think we can ignore unseen vs seen renewals for the moment, and assume the policy expresses unseen renewals (and leave it to staff to decide whether to renew an item the patron brings in)?

> there's currently no information in a loan policy that identifies it as being specifically for a reserve item (although we do usually put something in the description field about it).

Using the description text seems fine to me; we're just using it to provide clearer messaging about why a thing can't be renewed online.

**Comment by cbeer** [comment]
> folio loan policies have a string field called renewalsPolicy.renewFromId described as the "Renew from date". we currently only have one loan policy that has this field defined, and it's set to the string SYSTEM_DATE. i don't really know what this means...maybe it's a reference to another field on the loan object itself?

The FOLIO docs suggest `CURRENT_DUE_DATE` is another option; presumably it's when to start the renewal period (immediately, or extending the due date from the current due date), not a "you can renew this starting at X"

reopening for more investigation of that property 🤷‍♂️

**Comment by thatbudakguy** [comment]
Todo: make a new ticket to implement `#renewable_at` using FOLIO logic, including custom logic that takes account of `renewFromId`. This will be complicated and we need to do it together.

**Comment by thatbudakguy** [comment]
@corylown is this completed with https://github.com/sul-dlss/mylibrary/pull/858, https://github.com/sul-dlss/mylibrary/pull/859, etc?

**Comment by corylown** [comment]
@thatbudakguy Yes, I think it does.
