### ISSUE TITLE
Test all the APIs

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/folio-graphql#70]
- [x] authn-api
- [x] circulation-api
- [x] feefines-api
- [x] folio-api (maybe inherently tested by the others working?)
- [x] holdings-api
- [x] instances-api
- [x] items-api
- [x] okapi-api
- [x] types-api
- [x] users-api

You should be able to copy the example response objects from the FOLIO docs into our `mockResponse`  for each API test.
For example for the patrons-api test, [here](https://github.com/sul-dlss/folio-graphql/blob/9d94301f65b97f6eed19cb54edf1c69a2aa45ebb/__tests__/patrons-api.test.ts#L8) we copied the JSON from [FOLIO s3 docs](https://s3.amazonaws.com/foliodocs/api/mod-patron/p/patron.html#patron_account__id__get
), under "Example"

**Comment by hudajkhan** [comment]
It would be good to get a little more context: are these tests we're writing like patrons-api or are we testing out the APIs?

**Comment by marlo-longley** [comment]
Closed by #158
