### ISSUE TITLE
Revisit queueTotalLength

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/folio-graphql#83]
We ran into some unexpected logic around instance vs item level queues in FOLIO.
@saseestone will create more requests in the system so that we can come up with a strategy.
We may decide to call both the item and instance queues always, and add them together manually, rather than relying on totalRecords here https://github.com/sul-dlss/folio-graphql/blob/a84027ccf823ed8f522c0e7fbfa18f2b961e7f20/src/folio/circulation-api.ts#L8

Here is some related documentation: https://docs.folio.org/docs/access/requests/requests/#how-folio-decides-which-item-will-fill-a-title-level-request

**Comment by jcoyne** [comment]
I'm not sure what the action is here? Should we assign this to @saseestone?

**Comment by jcoyne** [comment]
Scenario:

There is an Instance (title) with two items (a & b)

User 1 places a hold on item a. The instance queue depth is 0 and item a's  queue depth is 1. 
User 2 places a hold on item a. The instance queue depth is 0 and item a's  queue depth is 2. 
User 3 places a hold on item b. The instance queue depth is 0 and item b's  queue depth is 1. 
User 4 places a hold on item b. The instance queue depth is 0 and item b's  queue depth is 2. 
User 5 places a hold on the instance. The instance queue depth is 1... (What should be the queue total length user 5 sees?)
User 6 places a hold on the instance.
User 7 places a hold on item a.  The instance queue depth is 2 and item a's queue depth is 3.... but we'd expect this person wouldn't get this item until use until 1 & 2 are fulfilled and possibly 5 or 6's.  The queue total length now has a minimum depth of 3 and a maximum depth of 5, average depth (assuming 5 & 6 are filled with separate items) of 4.

**Comment by jcoyne** [comment]
Typically an instance will only use the item queues or the title queue, not both at the same time.  Thus we can just use the sum of item + instance queue as the queue length, because either one or the other queue should be zero.

**Comment by jcoyne** [comment]
Given the decision above, I don't think there is any further action to be taken with this ticket.
